### ISSUE TITLE
Feedback for Request DKIM key for eu.mailgun.org

### ISSUE THREAD

**Issue by PetterNas** [SuperOfficeDocs/feedback#10]
[Enter feedback here]

The form to fill is missing, so not possible to request a DKIM at the moment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [order_dkim_key](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/email/mailgun/dkim/order-key.md/#L1)

**Comment by SuperOfficeDevNet** [comment]
Thanks for your feedback! 😸  The link has been fixed and will be published soon!🔗
