### ISSUE TITLE
Feedback for SuperOffice Docs

### ISSUE THREAD

**Issue by ejfasting** [SuperOfficeDocs/feedback#105]
https://docs.superoffice.com/en/apps/activate/helper-application.html#introducing-devnet-tokens

Wrong URI for the sample-application-callback.
The documentation says: 
https://devnet-tools.superoffice.com/openid/callback 

This should be: 
https://devnet-tokens.azurewebsites.net/openid/callback

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [SuperOffice Docs](https://docs.superoffice.com)

**Comment by AnthonyYates** [comment]
While we updated the docs because we prefer the devnet-tools.superoffice.com address, they will both work - assuming you have set the redirect uri correctly in the application configuration on https://dev.superoffice.com.
