### ISSUE TITLE
Feedback for CRMScript event handlers

### ISSUE THREAD

**Issue by MC-dragon** [SuperOfficeDocs/feedback#107]
[Enter feedback here]
From which version of SuperOffice should this type of Webhook  work, It would be nice to know this right in the spot. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [webhooks_crmscript_event_handlers](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/en/automation/webhook/crmscript-handlers.md/#L1)

**Comment by SuperOfficeDevNet** [comment]
Hi @MC-dragon!

This was added in Oct. 2020, released in 9.2.7648. The page has been updated and will be included in the next release.
