### ISSUE TITLE
Feedback for NetServer archive providers, missing letter in namespace

### ISSUE THREAD

**Issue by acdavidh** [SuperOfficeDocs/feedback#11]
The namespace mentioned in the Available archive providers section is missing a S.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [archive_providers](https://github.com/SuperOfficeDocs/data-access/blob/main/docs/netserver/archive-providers/index.md/#L1)

**Comment by SuperOfficeDevNet** [comment]
Thanks for your participation! 💯
