### ISSUE TITLE
Feedback for SOProtocol and web panels - web

### ISSUE THREAD

**Issue by MargretheR** [SuperOfficeDocs/feedback#110]
Here we mention crossmessaging, but it took me a while to locate the github example I knew we had on this.
Could we perhaps link to: https://github.com/SuperOffice/DevNet/tree/master/CrossMessaging

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [so_protocol_webpanel_web](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/en/ui/soprotocol/used-in-webpanels-web.md/#L1)

**Comment by digitaldiina** [comment]
![image](https://github.com/SuperOfficeDocs/feedback/assets/23242792/71c5c7c9-06a9-4483-b8e9-4880e56694c4)
