### ISSUE TITLE
Feedback for What's new in version 10.2.1.1517

### ISSUE THREAD

**Issue by Morten-git** [SuperOfficeDocs/feedback#112]
[Enter feedback here]

Nice info page (I have never seen before) with all DB changes?
It say "10.2.1.1517", but to me it seem like it is's a history of all changes. If the page contain all changes, it would be nice if each step have a SO Version number, then it will make it relatable when the change was applied. 
When customer (often onsite) ask what DB changes should we expect when we upgraded from version xx til version yy.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [database-whats-new-10.2.1.1517](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/release-notes/database/changes-10.2.1.md/#L1)

**Comment by SuperOfficeDevNet** [comment]
HI @Morten-git !

Yes, this has been around for a few years... 
With regards to better presenting JUST what has changed, we have two issues already created to address this. 

Issue [195](https://github.com/SuperOfficeDocs/superoffice-docs/issues/195) and [196](https://github.com/SuperOfficeDocs/superoffice-docs/issues/196)

One day...
