### ISSUE TITLE
Feedback for What's new in SuperOffice 10.2

### ISSUE THREAD

**Issue by acdavidh** [SuperOfficeDocs/feedback#115]
All links to the REST AGENT and SOAP agent for the new web service methods are wrong:

url listed:
https://docs.superoffice.com/en/docs/en/api/reference/restful/agent/Archive_Agent/v1ArchiveAgent_GetRelatedData.md

Actual link:
https://docs.superoffice.com/en/api/reference/restful/agent/Archive_Agent/v1ArchiveAgent_GetRelatedData.html

en/docs part is wrong

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [news-api-10.2](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/release-notes/10.2/api/index.md/#L1)

**Comment by SuperOfficeDevNet** [comment]
Not sure what you mean... All links to REST and SOAP endpoints work as expected when the site is published.

https://docs.superoffice.com/en/release-notes/10.2/api/index.html

**Comment by acdavidh** [comment]
> Not sure what you mean... All links to REST and SOAP endpoints work as expected when the site is published.
> 
> https://docs.superoffice.com/en/release-notes/10.2/api/index.html

If i click on one of the links I am redirected to the home page

![image](https://user-images.githubusercontent.com/40491305/216582071-8da41f8d-c9c7-4561-8bdf-0a154eb93748.png)

![image](https://user-images.githubusercontent.com/40491305/216582152-e0da49bc-8ab7-4ae4-9172-87695cf15029.png)

**Comment by SuperOfficeDevNet** [comment]
Oy! Browser cache issue... on my part... Not sure how || why... Will fix immediately...
