### ISSUE TITLE
Feedback for Code structure (syntax)

### ISSUE THREAD

**Issue by fbhub2** [SuperOfficeDocs/feedback#116]
missing languageLevel 4;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [crmscript_fundamentals_syntax](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/en/automation/crmscript/fundamentals/syntax.md/#L1)

**Comment by digitaldiina** [comment]
Added in https://github.com/SuperOfficeDocs/superoffice-docs/commit/de5f8dc24fc7e34e791aa6c8fccd562a52f97d82
