### ISSUE TITLE
Feedback for Extra fields

### ISSUE THREAD

**Issue by marcuss-so** [SuperOfficeDocs/feedback#117]
The "Extra Field Types" should include a technical definition of what kind of database-fields they result in. I'm especially interested in the number of characters allowed in Text (Short) and Text (Long) as well as ranges for the number fields.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [extra_fields](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/en/custom-objects/extra-field/index.md/#L1)

**Comment by digitaldiina** [comment]
Hi @marcuss-so, does this table of standard database fields help you?

https://docs.superoffice.com/en/database/getting-started/naming-conventions.html#standard-data-types-in-use

**Comment by digitaldiina** [comment]
Hi again @marcuss-so. We recently consolidated the custom-objects section and created a new page: https://docs.superoffice.com/en/custom-objects/reference/index.html 

Let me know if this answers your question.
