### ISSUE TITLE
Feedback for ODATA lists

### ISSUE THREAD

**Issue by MargretheR** [SuperOfficeDocs/feedback#119]
Seems docs examples is wrong here, it does not work with category. oneOf works fine with ticketTags however

It should work with category if you use in and not oneOf

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [odata_lists](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/en/api/search/odata/lists.md/#L1)

**Comment by xt1** [comment]
Bug in OData - oneOf and in work the same for non-tags fields now.

**Comment by digitaldiina** [comment]
@xt1 Does that mean we can close this issue with no docs update?

**Comment by xt1** [comment]
yes
