### ISSUE TITLE
Feedback for NetServer archive providers - Link indication

### ISSUE THREAD

**Issue by acdavidh** [SuperOfficeDocs/feedback#12]
Hello,

It isn't clear the text 'complete list of archive providers' is a link here, maybe underline in?

![image](https://user-images.githubusercontent.com/40491305/124264607-f9c2af00-db34-11eb-92a0-f91cbf3cc063.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [archive_providers](https://github.com/SuperOfficeDocs/data-access/blob/main/docs/netserver/archive-providers/index.md/#L1)

**Comment by SuperOfficeDevNet** [comment]
Thanks again @acdavidh for the feedback! We have bumps the hyperlink font-weight to 500 for all content articles, and now all the links are more pronounced in the UI.
