### ISSUE TITLE
Feedback for CM

### ISSUE THREAD

**Issue by MC-dragon** [SuperOfficeDocs/feedback#121]
[Enter feedback here]
CM.com does not work with a username / password  anymore with their API,  how to configure the CM.com plugin with a API token ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [cm_sms_plugin](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/en/service/sms/cm.md/#L1)

**Comment by digitaldiina** [comment]
@kronicz  can you look into this?

**Comment by kronicz** [comment]
@digitaldiina @MC-dragon Currently we are only supporting username/password, need to investigate how to support token instead. Usually providers do still support older legacy APIs, so suggest reaching out to provider for other options.
