### ISSUE TITLE
Feedback for ASP.NET web application quick-start

### ISSUE THREAD

**Issue by MargretheR** [SuperOfficeDocs/feedback#123]
The note on the page refers to filling out the update form to add redirects, it should refer to adding a new version of the configuration so their configuration may be edited while in SOD only if it is locked because it is published to stage/production

![image](https://github.com/SuperOfficeDocs/feedback/assets/22498774/9fedac6b-658d-4689-af78-b1a038a1a03e)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [auth_code_flow_quickstart](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/en/api/tutorials/auth-code-flow-quickstart.md/#L1)

**Comment by digitaldiina** [comment]
Merged in PR https://github.com/SuperOfficeDocs/superoffice-docs/pull/846
