### ISSUE TITLE
Feedback for Fields

### ISSUE THREAD

**Issue by samuelholmstroem** [SuperOfficeDocs/feedback#125]
[Enter feedback here]

This information is now outdated with the new Screean for Sales 

"The Details tab in the Sale screen"
We now have a more tab for Sales also. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [help-en-udef](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/en/custom-objects/learn/udef/index.md/#L1)

**Comment by SuperOfficeDevNet** [comment]
In addition, Sale link needs t update to correct page - which contains an image that needs to be updated with More tab, and needs an appended More section. 

https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/en/sale/learn/create.md#more-tab

**Comment by digitaldiina** [comment]
Updated in PR https://github.com/SuperOfficeDocs/superoffice-docs/pull/732
