### ISSUE TITLE
Feedback for User accounts and role-based access control

### ISSUE THREAD

**Issue by MargretheR** [SuperOfficeDocs/feedback#129]
Shouldn't this info about the functional rights be included in docs instead of an FAQ?
https://community.superoffice.com/en/support-faqs/faq/whichare-all-availablefunctional-rights-in-superoffice-and-what-each-of-them-mean/
Also note the FAQ links back to 8.1 help on community.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [user_accounts_roles](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/en/identity-management/user/index.md/#L1)

**Comment by digitaldiina** [comment]
Solved by issue https://github.com/SuperOfficeDocs/superoffice-docs/issues/816

The complete reference is at https://docs.superoffice.com/en/admin/user-management/learn/role/functional-rights.html
