### ISSUE TITLE
Feedback for Requirements

### ISSUE THREAD

**Issue by giedresuperoffice** [SuperOfficeDocs/feedback#130]
Hi, this lacks information like: that only MAIN account will work, shared mailbox will not work and etc. We and customers needs more information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [superoffice_for_outlook_requirements](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/en/email/superoffice-for-outlook/requirements.md/#L1)

**Comment by pavlas77** [comment]
@digitaldiina Fixed by PR #852 SOFO for Onsite. Can be closed, but dont know how, or dont have permissions.

**Comment by digitaldiina** [comment]
Thanks, @pavlas77. I'll close it.
