### ISSUE TITLE
Feedback for Office integration 10.2.7 update

### ISSUE THREAD

**Issue by marcuss-so** [SuperOfficeDocs/feedback#141]
For security focused organizations it might be valuable to be able to limit the Onsite API access to a limited IP adress or IP adress range.

If the calling server is using specific IP's, it would be great if those could be added to the docs for this feature. If not, I strongly suggest an architecture that makes this a possibility.

It should also be mentioned what kind of authentication that is used against the API, especially if it's Basic Auth and not OAuth. If OAuth is used, it needs to be explained how the renewal process is handled if the password gets changed. This to be able to help the customers administrators to be proactive in their information to the end users.

Question/Wish:
It would be great if it was possible to pre-set the URL-parameter centrally while registering the app in Azure, so the end customers don't have to fiddle with more than their name and password. Is that a possibility?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [news-office-integration-10.2.7](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/release-notes/10.2/office-integrations/3.1-update.md/#L1)

**Comment by digitaldiina** [comment]
@pavlas77 are you able to answer these questions?

**Comment by digitaldiina** [comment]
@marcuss-so, our primary focus on Docs is online. I suggest you reach out internally to Erik L or RnD Services. If you discover and write up these answers, I'll be happy to add your contribution to the site :)
