### ISSUE TITLE
Feedback for Run website on IIS localhost

### ISSUE THREAD

**Issue by acdavidh** [SuperOfficeDocs/feedback#142]
This FAQ seems very out of place, nothing to do with the developer portal. Maybe as a entry for the sample/demo apps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [run_website_on_iis_localhost](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/en/developer-portal/faq/run-website-on-iis-localhost.md/#L1)

**Comment by digitaldiina** [comment]
Thank you for the suggestion @acdavidh. I agree it doesn't pertain to the developer portal, but it's there as a resource for those just starting out. We'll leave it as-is for now.
