### ISSUE TITLE
Feedback for Which flow should you use?

### ISSUE THREAD

**Issue by ejfasting** [SuperOfficeDocs/feedback#146]
Should Implicit flow be removed from this page, as this page it links to say you should use Authorization Code Flow with PKCE instead (?). Suggestion would be to put '[Authorization Code flow](https://docs.superoffice.com/en/authentication/online/sign-in-user/auth-code-flow.html), WITH PKCE'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [online_auth_scenarios](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/en/api/authentication/online/which-flow-to-use.md/#L1)

**Comment by SuperOfficeDevNet** [comment]
It is still functional, so until we remove it, we just discourage from using it.
