### ISSUE TITLE
Feedback for Typical search

### ISSUE THREAD

**Issue by marcelspapens** [SuperOfficeDocs/feedback#147]
Is this document supposed to be in here? It looks like a design document, not public documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [undefined](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/en/api/search/find-selection/typical-search.md/#L1)

**Comment by digitaldiina** [comment]
Thanks again @marcelspapens🥇 I've included the typical search page in issue https://github.com/SuperOfficeDocs/superoffice-docs/issues/959. I'll close *this* issue. Please use the link if you have further questions or additional info.
