### ISSUE TITLE
Feedback for ms\_filter table

### ISSUE THREAD

**Issue by pavlas77** [SuperOfficeDocs/feedback#15]
List of the table names in the Reference menu. If a table has _ in the name, it is replaced by a space. 

And in the page title, underscore it prefixed with \, like s\_bounce\_shipment table

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [table-ms-filter](https://github.com/SuperOfficeDocs/database/blob/main/docs/tables/ms-filter.md/#L1)

**Comment by digitaldiina** [comment]
Thanks for the feedback @pavlas77. This reference is generated, so we need to fix this in the toolchain rather than in the database Markdown repository.

**Comment by SuperOfficeDevNet** [comment]
This is now fixed and published. 🚢 😃
