### ISSUE TITLE
Feedback for New Selection

### ISSUE THREAD

**Issue by xt1** [SuperOfficeDocs/feedback#16]
Where is the list of archive providers with columns?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [find_selection_intro](https://github.com/SuperOfficeDocs/data-access/blob/main/docs/netserver/search/find-selection/index.md/#L1)

**Comment by digitaldiina** [comment]
Hi and thanks for your question @xt1. 

The direct link is: http://docs.superoffice.com/api/netserver/archive-providers/reference/index.html

You can also find a link to it at the [SuperOffice API landing page](http://docs.superoffice.com/api/index.html) in the **Common API reference sections**.
