### ISSUE TITLE
Feedback for Creating follow-ups with your associates

### ISSUE THREAD

**Issue by Tonelofsgaard** [SuperOfficeDocs/feedback#161]
1. The terminology will change with the new Follow-up dialog,  from Participants to Attendees. We no longer have a Participants tab in the dialog either.
2. Having the View tab as starting point is probably a good idea and not wrong. This will change a lot visually when the new Diary comes with the new UI. We have though put a lot of effort into the Check availability dialog which is to be found inside the new Follow-up dialog. Is this mentioned somewhere or will it come later? The Check availability feature will be the new View tab in the future
3. The External contacts section is referring to the old dialog and is not valid for the new 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [help-en-invitation](https://github.com/SuperOfficeDocs/superoffice-docs/blob/827-new-follow-up-dialog/docs/en/diary/learn/invitation/index.md/#L1)

**Comment by digitaldiina** [comment]
1. This is too big to rewrite now. Let's add it for next release or GA. 
2. Commented on earlier :)
3. I deleted the External contacts section. Added the second half of the text to the classic dialog section of add-participants

**Comment by digitaldiina** [comment]
@Tonelofsgaard I created https://github.com/SuperOfficeDocs/superoffice-docs/issues/1022 on the backlog to tackle item 1.
