### ISSUE TITLE
Feedback for Add participants to follow-ups

### ISSUE THREAD

**Issue by Tonelofsgaard** [SuperOfficeDocs/feedback#162]
1. I have the same comment here - the term Participant is changing to Attenee with the new Follow-up dialog
2. Jeg vil tro det kommer en ny video siden denne bruker den gamle dialogen?
3. Toggle status is not supported in the new dialog...
4. Email invitation buttons heller ikke støttet i ny dialog.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [help-en-invitation-add-participant](https://github.com/SuperOfficeDocs/superoffice-docs/blob/827-new-follow-up-dialog/docs/en/diary/learn/invitation/add-participant.md/#L1)

**Comment by digitaldiina** [comment]
1. See previous comment.
2. No new videos until the new Diary UI.
3. (and 4) Need to postpone this for next version or GA. Let's prioritize the fixes in next docs backlog meeting.

**Comment by digitaldiina** [comment]
Terminology is has been updated and issues 3 and 4 are now supported in the dialog.
