### ISSUE TITLE
Feedback for Work with video meetings

### ISSUE THREAD

**Issue by Tonelofsgaard** [SuperOfficeDocs/feedback#163]
1. Again - I guess new video will be made with the new dialog
2. Also - this page seems to relate only to the old dialog....

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [help-en-video-meetings](https://github.com/SuperOfficeDocs/superoffice-docs/blob/827-new-follow-up-dialog/docs/en/diary/learn/video-meetings.md/#L1)

**Comment by digitaldiina** [comment]
1. No new videos until the new Diary UI.
2. Yes, I know. This image will be updated for GA of the Follow-up dialog. Changing it now will unfortunately mess with other pages that use this image.
