### ISSUE TITLE
Feedback for Moving follow-ups

### ISSUE THREAD

**Issue by Tonelofsgaard** [SuperOfficeDocs/feedback#164]
Her kan du også nevne at avtaler med deltakere ikke kan flyttes fra dagboka til aktivitetslista

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [help-en-follow-up-move](https://github.com/SuperOfficeDocs/superoffice-docs/blob/827-new-follow-up-dialog/docs/en/diary/learn/move-follow-up.md/#L1)

**Comment by digitaldiina** [comment]
Added a note. Thanks for the tip!
