### ISSUE TITLE
Feedback for Set alarm for follow-up - GDPR issues

### ISSUE THREAD

**Issue by kirstiaa** [SuperOfficeDocs/feedback#170]
Full name is in the image of Browser alarm - might be a good idea to blurry the sections that is not suppose to be seen.
I tried to do it here, but it got very blurry.

![edge-meeting-alarm](https://github.com/SuperOfficeDocs/feedback/assets/102585577/b69031a3-d016-42bb-99c4-13ec8257a12e)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [help-en-follow-up-alarms](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/en/diary/learn/set-alarm.md/#L1)

**Comment by digitaldiina** [comment]
Thanks for your concern, @kirstiaa but there is no sensitive data here. My name is all over docs, both in metadata and screenshots, and that is my choice.
