### ISSUE TITLE
Feedback for Dialog for follow-ups

### ISSUE THREAD

**Issue by kirstiaa** [SuperOfficeDocs/feedback#175]
The page consist of mostly old information, how the follow-up dialog was before the new one came.
Need more info about Title field, Agenda + Internal notes + new naming of functionality.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [help-en-dialog-for-followups](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/en/diary/learn/screen/dialog-for-followups.md/#L1)

**Comment by digitaldiina** [comment]
This page is ONLY for the old dialog, as **stated in the note**:

![image](https://github.com/SuperOfficeDocs/feedback/assets/23242792/06cba1df-4c0e-413f-a8b2-1b8364d90a38)

This page will be archived after the new Follow-up dialog reaches general availability.
