### ISSUE TITLE
Feedback for Enum values for ModifiedAppointmentFields

### ISSUE THREAD

**Issue by Morten-git** [SuperOfficeDocs/feedback#177]
Is it possible to list possible values.
At an appointment I look at right now I see values have been 0, 4, 6, 7.
But what "important fields of an appointment" is that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [enum-modifiedappointmentfields](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/en/database/tables/enums/modifiedappointmentfields.md/#L1)

**Comment by SuperOfficeDevNet** [comment]
Hi @Morten-git !

Unfortunately these files in the documentation are generated, and not always logical.

The possible values are based on the following enum as flags.
```csharp
    /// <summary>
    /// Value for field &apos;modified_appointment_fields&apos; in table &apos;appointment&apos;.
    /// </summary>
    [Flags]    
    public enum ModifiedAppointmentFields 
    {
        /// <summary>
        /// 0: No modified fields.
        /// </summary>
        None = 0,
        
        /// <summary>
        /// 1: The Date-field has been modified.
        /// </summary>
        Date = 1,
        
        /// <summary>
        /// 2: The Time-field has been modified.
        /// </summary>
        Time = 2,
        
        /// <summary>
        /// 4: The Location-field has been modified.
        /// </summary>
        Location = 4,
    }
```

Therefore:

0 = None
1 = Date
2 = Time
3 = Date and Time
4 = Location
5 = Location and Date
6 = Location and Time
7 = Date and Time and Location

Hope this helps!

**Comment by Morten-git** [comment]
This definitely helps.
Thanks
(But some time in the future I might forget)
