### ISSUE TITLE
Feedback for Resource_Agent / agent method list

### ISSUE THREAD

**Issue by acdavidh** [SuperOfficeDocs/feedback#187]
This looks broken to me;

![image](https://github.com/SuperOfficeDocs/feedback/assets/40491305/2ca2def2-be58-4cd3-bfdb-958e6b736b9b)

(Happens for all agents)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [undefined](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/en/api/reference/restful/agent/Resource_Agent/index.md/#L1)

**Comment by SuperOfficeDevNet** [comment]
Yes, it's a known issue I'll fix next week.

**Comment by acdavidh** [comment]
This was fixed by update for 10.3.2 release
