### ISSUE TITLE
Database - Tables: ticket_type shows incorrect fields

### ISSUE THREAD

**Issue by baskreijveld** [SuperOfficeDocs/feedback#190]
Hi all,

It seems that the ticket_type references (Fields) are mostly incorrect:

https://docs.superoffice.com/en/database/tables/ticket-type.html

The visual overview below seems to be more in line with what is available / how it works.

**Comment by SuperOfficeDevNet** [comment]
Hi Bas! 

You are correct! We will work on this.

Best regards!

**Comment by SuperOfficeDevNet** [comment]
The database reference has been updated.
