### ISSUE TITLE
TaskType Enum is missing actual integers used by the list

### ISSUE THREAD

**Issue by marcuss-so** [SuperOfficeDocs/feedback#194]
### What is the current behavior?
(https://docs.superoffice.com/en/automation/crmscript/reference/CRMScript.NetServer.TaskType.html)

The enum list is missing the actual integers for the list.

Also, this part of docs doesn't seem to have a feedback-button or Git-button, which would have been nice.

### What changes are you suggesting?
I wold like the integer-number for the items in the enum list to be added to the docs.

Best Regards
Marcus

**Comment by digitaldiina** [comment]
Thanks for the feedback @marcuss-so. Adding the Feedback/Git button to API references is on our list.

We currently do not list integer values for any of the CRMScript enums, as far as I can tell. This reference is manually maintained at the moment, and it is unlikely that we add a value column before we automate NetServer types for CRMScript (see issue https://github.com/SuperOfficeDocs/superoffice-docs/issues/203).

However, you can find the integer values in the [database reference](https://docs.superoffice.com/en/database/tables/enums/tasktype.html).

We also have a [sample CRMScript you can run to list task types](https://docs.superoffice.com/en/diary/howto/crmscript/plan-outgoing-call.html) (using SearchEngine).
