### ISSUE TITLE
Feedback for downloads

### ISSUE THREAD

**Issue by acdavidh** [SuperOfficeDocs/feedback#20]
The layout is broken
![image](https://user-images.githubusercontent.com/40491305/129525563-fd3cea46-0f83-44ad-9d0a-36746c6fcc01.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [undefined](https://github.com/SuperOfficeDocs/data-access/blob/main/docs/assets/downloads.md/#L1)

**Comment by digitaldiina** [comment]
Hi and thanks for the feedback. We're aware of this and fixed it in https://github.com/SuperOfficeDocs/data-access/issues/48. You should see the change the next time we push an update to the site.
