### ISSUE TITLE
Feedback for User plans

### ISSUE THREAD

**Issue by MargretheR** [SuperOfficeDocs/feedback#200]
Marketing premium, just to put into the backlog that this page needs to be updated with new info about this

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [user_plans](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/en/admin/license/user-plans.md/#L1)

**Comment by digitaldiina** [comment]
@MargretheR I'll handle this in issue https://github.com/SuperOfficeDocs/superoffice-docs/issues/829 :)
