### ISSUE TITLE
Feedback for Permissions in SharePoint

### ISSUE THREAD

**Issue by rqbbz** [SuperOfficeDocs/feedback#206]
Dont understand why you recommed the user of "Microsoft 365 group" instead of Security group. it is even a warning.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [config-sharepoint-permissions-documents](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/en/document/cloud/sharepoint-documents/configure-permissions-documents.md/#L1)

**Comment by digitaldiina** [comment]
@pavlas77 could you answer this question, please? Thanks in advance.

**Comment by digitaldiina** [comment]
Hi @rqbbz, I've discussed this with the team.

Microsoft 365 group is required to set CRM access control (Visible for).

**Comment by digitaldiina** [comment]
Closing this issue as it has been addressed. If you have any further questions or suggestions, feel free to reach out again.
