### ISSUE TITLE
Feedback for Create a new flow

### ISSUE THREAD

**Issue by smedbrat** [SuperOfficeDocs/feedback#211]
1) Had chat and order places is not yet implemented as triggers. We are awaiting feedback from pilots as they may prioritize other triggers instead.

2) The following sentence might be mixing up triggers and filters a bit: "For example, set the filter to contact category = prospect to trigger a flow only for prospects, not existing customers," Suggested sentence: For example, set the filter to contact category = prospect to only allow prospects into the flow, not existing customers,

3) I found this info a bit confusing:
"Filters apply only when identifying flow participants. In an ongoing flow, contacts may be removed if they fulfill the success criteria."
Suggestion: "Filters apply only when identifying new flow participants. Changes made later to the filter does not affect participants already added."

4) Exclusion list: We have improved the text a bit in the UI based on feedback, consider making a new screen dump.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [help-en-flow-create](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/en/marketing/flows/learn/create.md/#L1)

**Comment by digitaldiina** [comment]
Solved in https://github.com/SuperOfficeDocs/superoffice-docs/issues/1179.


@smedbrat please let me know if/when you add more triggers
