### ISSUE TITLE
Feedback for Define flow actions

### ISSUE THREAD

**Issue by smedbrat** [SuperOfficeDocs/feedback#213]
1) "Creating activities also lets you focus on contacts who are engaged and wants it​."  Wants what? seem sentence is ended a bit sudden.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [help-en-flow-actions](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/en/marketing/flows/learn/define-flow-actions.md/#L1)

**Comment by xt1** [comment]
Drop "and wants it".


--
Christian Mogensen
Product Developer
SuperOffice AS

"Any fool can write code that a computer can understand.
Good programmers write code that humans can understand."

--Martin Fowler


________________________________
From: smedbrat ***@***.***>
Sent: 10 May 2024 10:48
To: SuperOfficeDocs/feedback ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [SuperOfficeDocs/feedback] Feedback for Define flow actions (Issue #213)


  1.  "Creating activities also lets you focus on contacts who are engaged and wants it​." Wants what? seem sentence is ended a bit sudden.

________________________________
Document Details

⚠ Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.

  *   Content Source: help-en-flow-actions<https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/en/marketing/flows/learn/define-flow-actions.md/#L1>

**Comment by digitaldiina** [comment]
Solved in https://github.com/SuperOfficeDocs/superoffice-docs/issues/1179
