### ISSUE TITLE
Feedback for Step settings

### ISSUE THREAD

**Issue by smedbrat** [SuperOfficeDocs/feedback#215]
Split settings: 
1) Everyone else | Participants who match no criteria get status "drop out".  --> Everyone else is the branch for handling those who do not meet the conditions of any of the other branches. They do not necessarily drop out, the may continue in the everyone else branch too.
2) Exit flow | Whether dropped-out participants should leave the flow. -->  Whether or not those who do end up in everyone-else branch should drop out or not. (They are not dropped-out participants unless exit is true, and then they drop out)

3) Trigger - Filter | A set of criteria that must be met before a suggested contact starts a flow. --> Suggestion: "A set of criteria that must be met for a suggested contact to be allowed into the flow". Avoiding any confusion, as the contact will not continue in the flow later if he fulfills these criteria, they are only checked once.

4) Trigger - Exclusion list: Update text according to the one in use in the UI now?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [help-en-flow-step-settings](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/en/marketing/flows/learn/step-settings.md/#L1)

**Comment by digitaldiina** [comment]
Solved in https://github.com/SuperOfficeDocs/superoffice-docs/issues/1179
