### ISSUE TITLE
Feedback for View statistics for flow

### ISSUE THREAD

**Issue by smedbrat** [SuperOfficeDocs/feedback#216]
1) Related to the Tip: We have changed the implementation to refresh button in archive footer for all tabs, no longer a refresh arrow in upper right corner.
2) Trigger is missing an explanation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [help-en-flow-view-statistics](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/en/marketing/flows/learn/view-statistics.md/#L1)

**Comment by digitaldiina** [comment]
Solved in https://github.com/SuperOfficeDocs/superoffice-docs/issues/1179
