### ISSUE TITLE
Feedback for Database table listing

### ISSUE THREAD

**Issue by atasdo** [SuperOfficeDocs/feedback#220]
Hi,

Some tables have a URL link to techdoc.superoffice.com in their table description
That is an old URL. 

Maybe we can change/remove it. 

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [database-table-listing-by-name](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/en/database/tables/index.md/#L1)

**Comment by digitaldiina** [comment]
Thanks @atasdo. Please see SuperOfficeDocs/superoffice-docs#1208
