### ISSUE TITLE
Feedback for Centralized deployment

### ISSUE THREAD

**Issue by ErikLebiko** [SuperOfficeDocs/feedback#225]
Hi, I see that the section regarding Deploy using the admin center could be replaces with a link to the learn.microsoft.com. Currently we suggest changing to old Admin Center GUI, to my knowledge that is not longer possible for instance. Link means there will be less maintenance in the future too, since things have a tendency to change over time. 

Here is the link: https://learn.microsoft.com/en-us/microsoft-365/admin/manage/manage-deployment-of-add-ins?view=o365-worldwide

I actually made a suggestion, see PR

/Erik 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [deploy_superoffice_for_outlook_centrally](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/en/email/superoffice-for-outlook/deploy-centrally.md/#L1)

**Comment by ErikLebiko** [comment]
Adding add-ins with URL does not work anymore, so we need to remove the section from PowerShell. I made all the changes in the post, se Pr
/Erik

**Comment by digitaldiina** [comment]
Solved by PR https://github.com/SuperOfficeDocs/superoffice-docs/pull/1245

Thanks for the suggestion and your contribution @ErikLebiko  ✔
