### ISSUE TITLE
Feedback for Video meetings

### ISSUE THREAD

**Issue by FBSOLT** [SuperOfficeDocs/feedback#239]
[It needs to be added, that MS Authenticator should be activated for SuperOffice login for MS Teams links to work as videomeeting provider.
MS business account is required for MS Authenticator - family account does not give access to Authenticator/MS Login/soazuread.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [help-en-video-meetings-tab](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/en/admin/preferences/learn/video-meetings/index.md/#L1)

**Comment by digitaldiina** [comment]
Transferred #240 to the backlog and will update both pages within the same issue there. Closing this one.

Thanks again 💯
