### ISSUE TITLE
Feedback for User-defined fields explained

### ISSUE THREAD

**Issue by FBSOLT** [SuperOfficeDocs/feedback#242]
[The language code lists
![image](https://github.com/user-attachments/assets/8169b1f2-c025-424f-ab6e-16a6876ee848)
]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [help-en-udef](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/en/custom-objects/learn/udef.md/#L1)

**Comment by digitaldiina** [comment]
Thanks! Included table in https://github.com/SuperOfficeDocs/superoffice-docs/issues/1323
