### ISSUE TITLE
Feedback for Add extra fields

### ISSUE THREAD

**Issue by FBSOLT** [SuperOfficeDocs/feedback#243]
[Add language codes for new fields. The string: <US:"Text1234";DA:"Tekst1234";SW:"Text1234";GE:"Text1234";NO:"Tekst1234">
![image](https://github.com/user-attachments/assets/62e4dac3-7ca7-4fa5-8b81-19f6564917d5)
]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [help-en-extra-fields-create](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/en/custom-objects/admin/create-extra-field.md/#L1)

**Comment by digitaldiina** [comment]
Part of #242
