### ISSUE TITLE
Feedback for SuperOffice AI Services

### ISSUE THREAD

**Issue by FBSOLT** [SuperOfficeDocs/feedback#246]
[A blank page see below - it is in search, not here:
![image](https://github.com/user-attachments/assets/59368b39-7d24-48d7-92bf-07ce8e3362b5)
]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [ai-services](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/en/ai/index.md/#L1)

**Comment by digitaldiina** [comment]
@FBSOLT we tested some Copilot features earlier. The chat page is retired and no longer shows up in search results.
