### ISSUE TITLE
Feedback for Variables from the Project card

### ISSUE THREAD

**Issue by samuelholmstroem** [SuperOfficeDocs/feedback#257]
We are saying "_formatted 02.11.2025 (system format)_) But I still don´t know if this is dd.mm.yyyy or mm.dd.yyyy 
Can we specify this wither by using a date that is not a month **25**.11.2025  or 02.**27**.2024 or actually showing it as dd.mm.yyyy or mm.dd.yyyy 

So that it´s better displays what this format means. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [help-en-tempvar-project-card](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/en/document/templates/variables/from-project-card.md/#L1)

**Comment by digitaldiina** [comment]
Hi @samuelholmstroem, this is a good question, but unfortunately we cannot specify if this is dd.mm.yyyy or mm.dd.yyyy. It depends. **System format** is set by the users selected culture.

You can [read more about culture in the Globalization setction ](https://docs.superoffice.com/en/globalization-and-localization/#ui-culture-vs-culture-in-net)

Related, users can also go to **Personal settings** > **Local settings** and set **Number and date format**.
