### ISSUE TITLE
Feedback for Mobile CRM 11.0.3 update

### ISSUE THREAD

**Issue by filipjnorman** [SuperOfficeDocs/feedback#263]
Hi, I don´t get this capabilities on my iPhone. Do you need to do something special to activate this?

Best regards
Filip

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [news-mobile-crm-11.0.3](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/release-notes/mobile/11.0.3-update.md/#L1)

**Comment by SuperOfficeDevNet** [comment]
Hi Filip!

As it states "Available for mobile devices running Android OS.", this is an Android only widget... not on the iPhone. The iPhone has a completely different time and date picker widget... the standard one for many years. It would be wrong to use something else.

We will remove that statement about "it" being on the iPhone - that is a misleading statement. 

Thanks for your feedback! 💯
