### ISSUE TITLE
Feedback for Quote templates and merge fields

### ISSUE THREAD

**Issue by FBSOLT** [SuperOfficeDocs/feedback#265]
For this https://docs.superoffice.com/en/document/templates/learn/quote-templates.html#quote-details-template
Is there a reason why only "Send" and NOT "Preview" is mentioned here. Both seems to work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [help-en-quote-template](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/en/document/templates/learn/quote-templates.md/#L1)

**Comment by digitaldiina** [comment]
I believe the intent was to generate the document, which the preview doesn't do. That said, RnD teams have worked on improving the Quote dialogs and UI, and the docs will be updated to reflect these changes. I'll keep preview in mind when I rewrite that section :)

**Comment by FBSOLT** [comment]
Thank you! I do get a PDF document by pressing "preview" - I believe, you will write it in a clear way, when the update comes.
I do enjoy our communication and your responses. (Let me know, if my tone is too direct)
