### ISSUE TITLE
Feedback for Clone

### ISSUE THREAD

**Issue by MargretheR** [SuperOfficeDocs/feedback#266]
There are 24 steps in the guide, but 31 in reality. It is step 7 that is taking forever.

Correct steps: 
Wait for customer tasks to complete and enter offline maintenance mode
Wait for customer task to complete	
Connecting customer to old clusters
Remove Mail Routes
Drop database
Create Customer Database
Create SQL login
Copy customer database from XXX to ZZZ
Prepare cloned database for target customer
Create SQL login
Disable Scheduled Tasks
Fix system users	
Replacing all personal email domains with '@mailinator.com'	
Register Customer In SuperId	
Replace Test Environment in SuperId	
Clone Azure Templates from CUST on ARCHIVEServer
Verify or provision Mail Service		
Set database permissions for Customer Query	
Recycle customer
Change serial number to TEST NAME/ SERIALNUMBER
Set SuperId Tenant State to: In migration	
Assign user plans		
Sync Customer SuperId Users	
Set SuperId Tenant State to: Normal	
Create Partner System Users From App Authorizations in Customer Database	
Update Company Info and License		
Clone EjPackages in Azure from CustID
Clone EjPackages in SoArc from CustID
Notify apps about Changing State with BackupRestored		
Enter Running Mode	
Wait for customers IIS ApplicationHost.config operations to complete
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [clone_to_sandbox_steps](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/en/online/sandbox/clone-to.md/#L1)

**Comment by digitaldiina** [comment]
Thank's @MargretheR, I'll combine this with issue SuperOfficeDocs/superoffice-docs#1574  from @JanBonde and move that to the backlog.
