### ISSUE TITLE
Enum values incorrect in NetServer WidgetRequiredFields

### ISSUE THREAD

**Issue by digitaldiina** [SuperOfficeDocs/feedback#27]
Wrong: https://docs.superoffice.com/api/reference/netserver/core/SuperOffice.Data.WidgetRequiredFields.html
Correct: https://docs.superoffice.com/api/reference/crmscript/classes/NSChatWidgetSettings/GetOfflineFields.html

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [SuperOffice Docs](https://docs.superoffice.com)

**Comment by SuperOfficeDevNet** [comment]
Already [updated](https://github.com/SuperOfficeDocs/data-access/blob/main/docs/api-reference/netserver/core/SuperOffice.Data.WidgetRequiredFields.yml)... Added earlier today in [this commit](https://github.com/SuperOfficeDocs/data-access/commit/ead0c764c6d9ae8c50d36717fb31434e3ddefc23)
