### ISSUE TITLE
Feedback for Bulk update

### ISSUE THREAD

**Issue by FBSOLT** [SuperOfficeDocs/feedback#278]
The first sentence: "Bulk update allows you to change values across multiple records of the same type. You can perform the bulk update on all or selected records in section tabs (archives), selections and the Find screen. This task can also be used to delete multiple records." 
For me it is unclear that "selections" in Dashboards are included. Maybe just my reading of "selections"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [help-en-bulk-update](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/en/learn/basics/bulk-update.md/#L1)

**Comment by digitaldiina** [comment]
A dashboard is a way of displaying various types of data. A selection can be used as a dataset for a dashboard. However, the data is still tied to the selection. Updates to the selection will be reflected in the dashboard. Does this clarify things?

**Comment by FBSOLT** [comment]
Yes. I hope that customers have the same understanding of a selection is the basis for a dashboard and thereby read Dashboard when they read selection.

**Comment by digitaldiina** [comment]
The [dashboard start page](https://docs.superoffice.com/en/dashboard/learn/index.html#terminology) has a terminology section, which I think is sufficient in this case. So I'll close the issue for now.
