### ISSUE TITLE
Feedback for Video Meetings for SuperOffice - Microsoft Teams

### ISSUE THREAD

**Issue by ChristianSUO** [SuperOfficeDocs/feedback#283]
Hi,
is it correct, that the SuperOffice cutomer and the invited person need a special MS Teams license (Teams Professional or something like that) to be able to use it? I have heard, that without this license, the link will not work correctly?!?!
If yes, we should infrom our customers in the Requirement section.

Best regards,
Christian

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [video_meetings_msteams](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/en/video-meeting/ms-teams/index.md/#L1)

**Comment by digitaldiina** [comment]
This seems to be a duplicate to https://github.com/SuperOfficeDocs/superoffice-docs/issues/1324. Specifics have not been confirmed yet.

**Comment by digitaldiina** [comment]
@ChristianSUO Video meetings with Microsoft Teams **require a subscription to Microsoft 365 for business**, not for home. The latter category includes Personal and Family.

Thanks for the reminder. The docs will be updated with this info shortly.
