### ISSUE TITLE
Feedback for Troubleshooting migration errors

### ISSUE THREAD

**Issue by MargretheR** [SuperOfficeDocs/feedback#289]
Point 6 - can we add this to the note as well: SQL instances needs two \\ or you'll get a "CS1009: Unrecognized escape sequence"

Databasserver\\instans

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [troubleshooting_migration_errors](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/en/online/migrate/troubleshooting.md/#L1)

**Comment by SuperOfficeDevNet** [comment]
Not our place to teach how to escape a connection string in code.
