### ISSUE TITLE
Feedback for Authorization Code flow

### ISSUE THREAD

**Issue by MargretheR** [SuperOfficeDocs/feedback#30]
Missing picture under Verify the JWT - ![JWT Claims][img2]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [auth_code_flow](https://github.com/SuperOfficeDocs/data-access/blob/main/docs/authentication/online/sign-in-user/auth-code-flow.md/#L1)

**Comment by SuperOfficeDevNet** [comment]
Updated 💯 👍
