### ISSUE TITLE
Feedback for Variables for a selected contact

### ISSUE THREAD

**Issue by acdavidh** [SuperOfficeDocs/feedback#31]
Table format is broken at ati variable

![image](https://user-images.githubusercontent.com/40491305/136916896-6048b143-1684-4a2b-9553-e82a860886cc.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [variables_for_selected_contact](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/document/templates/variables/for-selected-contact.md/#L1)

**Comment by SuperOfficeDevNet** [comment]
Thanks for your contribution! 👍 💯
