### ISSUE TITLE
Feedback for Tested client OS

### ISSUE THREAD

**Issue by acdavidh** [SuperOfficeDocs/feedback#33]
Hello,

Has any testing for Windows 11 been done?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [tested_client_os](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/onsite/compatibility/client-os.md/#L1)

**Comment by digitaldiina** [comment]
Do you have any insights to share on this, @pavlas77 ?

**Comment by pavlas77** [comment]
Not yet, I know about it. It depends on Sri Lanka when they do the testing.

**Comment by digitaldiina** [comment]
@acdavidh This was resolved in issue https://github.com/SuperOfficeDocs/superoffice-docs/issues/142. 

Clicking the content source link in the issue description above will show the updated page. Does this answer your question?

**Comment by acdavidh** [comment]
Yes, great!
