### ISSUE TITLE
Feedback for Helper for private applications

### ISSUE THREAD

**Issue by acdavidh** [SuperOfficeDocs/feedback#37]
Broken reference to image

![image](https://user-images.githubusercontent.com/40491305/140936936-80513d1c-1012-411f-8e6a-17084b274006.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [helper_application](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/apps/activate/helper-application.md/#L1)

**Comment by digitaldiina** [comment]
Thanks so much for contributing this fix @acdavidh . PR is approved and merged :)
