### ISSUE TITLE
Feedback for Reuirements

### ISSUE THREAD

**Issue by acdavidh** [SuperOfficeDocs/feedback#44]
The title is missing a q, requirements instead of reuirements.

also the sentence "To make the view of the SAP documents available in SuperOffice CRM Online" seems out of place here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [mirroring_requirements](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/mirroring/requirements.md/#L1)

**Comment by digitaldiina** [comment]
Thanks for your contribution, @acdavidh ! PR is approved and merged, so I'm closing this issue now.
