### ISSUE TITLE
Feedback for Introduction to SuperOffice APIs

### ISSUE THREAD

**Issue by jbergens** [SuperOfficeDocs/feedback#48]
Is the documentation for the old api's available somewhere?

We would like to see any api for version 8.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [intro-to-superoffice-apis](https://github.com/SuperOfficeDocs/data-access/blob/main/docs/getting-started/index.md/#L1)

**Comment by SuperOfficeDevNet** [comment]
The closest thing to versioned API's are the SOAP API's. The NuGet package [SuperOffice.NetServer.Services](https://www.nuget.org/packages/SuperOffice.NetServer.Services) uses these endpoints. While the client proxies versioning strategy did align with SuperOffice releases, the underlying API's - dependencies on services versions, did not. For example, SuperOffice 8, had compatibility with services83.

![image](https://user-images.githubusercontent.com/15157161/146387109-9d0d7393-bcca-4c75-87fc-ce8863708ca0.png)

There is very little different between what you would find in services84 compared to services83, so I would recommend you give the [versioned SOAP](https://docs.superoffice.com/api/reference/soap/Services84/index.html) docs a peek.

Hope this helped.
