### ISSUE TITLE
Feedback for Create WFC

### ISSUE THREAD

**Issue by MargretheR** [SuperOfficeDocs/feedback#51]
You get the private certificate key for SOD from SuperOffice. You must provide your own certificates for the stage and production environments.
->
You get the private certificate key for SOD from SuperOffice. You COULD provide your own certificates for the stage and production environments. We do generate them her and send them via sendsafely.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [create_mirroring_wfc](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/mirroring/getting-started/create-wfc.md/#L1)

**Comment by SuperOfficeDevNet** [comment]
Fixed.
