### ISSUE TITLE
Feedback for Variables for service

### ISSUE THREAD

**Issue by acdavidh** [SuperOfficeDocs/feedback#54]
Align examples of csbl and cscu so that it's clear that you get the full url:

![image](https://user-images.githubusercontent.com/40491305/153154411-b90e52ca-38c7-4150-93d0-26dd589cc3ab.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [variables_for_service](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/document/templates/variables/for-service.md/#L1)

**Comment by digitaldiina** [comment]
Thanks for the fix, @acdavidh ! Love your contributions. I'll close this issue now since the PR has been merged.
