### ISSUE TITLE
Feedback for Add tables to skip mirroring

### ISSUE THREAD

**Issue by MargretheR** [SuperOfficeDocs/feedback#56]
And a new preference has surfaced, we can actually change the size of bulks sent to the mirror by adding a preference
We send by default 1MB of rawdata 
Preference [prefsection] = 'Mirroring' and [prefkey] = 'BatchSize'  change prefValue to something other than the default (in bytes)  default = 1000000. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [skip_tables](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/mirroring/skip-tables.md/#L1)

**Comment by SuperOfficeDevNet** [comment]
Added to the [mirroring tasks](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/mirroring/mirroring-task.md) document
