### ISSUE TITLE
Feedback for Placeholder TBD

### ISSUE THREAD

**Issue by acdavidh** [SuperOfficeDocs/feedback#63]
Title seems like a _placeholder_ ;)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [undefined](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/api/web-services/introduction.md/#L1)

**Comment by SuperOfficeDevNet** [comment]
Hi David. 

Work in progress, or a scrap of a page that isn't included anywhere ... but I see the point. Seems search is exposing it.

**Comment by SuperOfficeDevNet** [comment]
Removed.
