### ISSUE TITLE
Feedback for What's new

### ISSUE THREAD

**Issue by fbhub2** [SuperOfficeDocs/feedback#66]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [whats_new_db](https://github.com/SuperOfficeDocs/database/blob/main/docs/whats-new/index.md/#L1)

**Comment by fbhub2** [comment]
https://docs.superoffice.com/database/whats-new/index.html
say:  "Use the table of contents on the left side to find the version you're looking for."
- but the table of contents is not auto-set to view this - and finding it in the table of contents is not easy.

**Comment by fbhub2** [comment]
I assume the correct reference is : https://docs.superoffice.com/release-notes/database/index.html

**Comment by digitaldiina** [comment]
Thanks for the feedback, Frode. The page has been moved but the old page is still on the server/cache/search index. It should correct itself on the next update. @SuperOfficeDevNet
