### ISSUE TITLE
Feedback for Introduction

### ISSUE THREAD

**Issue by superadde** [SuperOfficeDocs/feedback#71]
The link to the integration in our appstore is broken:
"Read more details in our App Store: [Microsoft 365 integration](https://online.superoffice.com/AppStore/superoffice-as/office-365-integration)"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [microsoft_365_document_integration](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/document/cloud/office-365/index.md/#L1)

**Comment by digitaldiina** [comment]
Thanks for letting us know, @superadde .

The app is no longer available and will be replaced by SuperOffice SharePoint Documents. We are working on documenting the new solution. I'd be happy to share the link to the new docs here when we release them.

**Comment by SuperOfficeDevNet** [comment]
New [Sharepoint documentation section](https://docs.superoffice.com/document/cloud/sharepoint-documents/index.html) published awhile ago, closing this issue.
