### ISSUE TITLE
Feedback for Developer Portal

### ISSUE THREAD

**Issue by xt1** [SuperOfficeDocs/feedback#73]
Missing link to developer portal

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [developer-portal-overview](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/developer-portal/overview.md/#L1)

**Comment by digitaldiina** [comment]
@xt1 The portal is not yet officially released and thus we don't want to direct traffic there just yet.
