### ISSUE TITLE
Feedback for Developer Products

### ISSUE THREAD

**Issue by MargretheR** [SuperOfficeDocs/feedback#86]
DevelopMENT tools and products :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [undefined](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/release-notes/10.0/developer-products/index.md/#L1)

**Comment by MargretheR** [comment]
Cache issue?
![image](https://user-images.githubusercontent.com/22498774/194534708-1c369fa1-c528-49d9-beb8-799e7126cc12.png)

**Comment by MargretheR** [comment]
![image](https://user-images.githubusercontent.com/22498774/194535174-9833c658-015d-4ea7-9d45-073aae5821aa.png)

**Comment by SuperOfficeDevNet** [comment]
This is an old artifact. As there is a corrected version in place, we have removed this and re-ran the search index.
