### ISSUE TITLE
Feedback for SharePoint documents

### ISSUE THREAD

**Issue by superd1984** [SuperOfficeDocs/feedback#90]
[Enter feedback here]

this link should be not active anymore. Information is not up to date. Corrert link for this article is now: https://docs.superoffice.com/document/cloud/legacy/office-365/set-up.html

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [sharepoint-documents](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/document/cloud/sharepoint-documents/index.md/#L1)

**Comment by digitaldiina** [comment]
Thanks for your feedback, @superd1984 :)

You're correct in that the link for the **old** integration should point to the legacy folder. However, the sharepoint-documents page listed as source here has been written with the **new** "SharePoint Online Documents" integration in mind. Both pages are valid, for different integrations.

If there's incorrect information about SharePoint Online Documents on the page, please point out the specifics and we'll update the page.

**Comment by pavlas77** [comment]
@digitaldiina You wrote: You're correct in that the link for the old integration should point to the legacy folder.

I can't find what he means, or you, what is wrong. Please point me to the correct place.

**Comment by digitaldiina** [comment]
The page was updated in May this year. Unable to reproduce behavior at this point.
