### ISSUE TITLE
Feedback for Screenshots for the App Store

### ISSUE THREAD

**Issue by MargretheR** [SuperOfficeDocs/feedback#98]
Broken link under Creating screenshots 
[Checking the details of an image is very simple.](https://fusionyearbooks.zendesk.com/hc/en-us/articles/207067043-How-do-I-check-for-photo-resolution) (article)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [how-to-create-good-screenshots](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/apps/publish/screenshots.md/#L1)

**Comment by digitaldiina** [comment]
Resolved by PR https://github.com/SuperOfficeDocs/superoffice-docs/pull/569
