### ISSUE TITLE
Feedback for Images and videos

### ISSUE THREAD

**Issue by MargretheR** [SuperOfficeDocs/feedback#99]
Following text must be changed from: "We will take the submitted information and clean screenshots, and create an appealing screenshot that matches a certain level of consistency with the App Store."

To something like
"The screenshots of your apps are being used to showcase your app. The images must be as crisp as possible.

Your screenshots are viewed on different screen resolutions. To guarantee readability, the minimum dimensions of your screenshots should be 1920x1080, but we prefer the double sizes of 3840x2160; this makes the screenshot crystal clear on Apple retina screens.

We will make sure that your screenshot fits the style of the SuperOffice App Store; t[here](https://docs.superoffice.com/apps/publish/screenshots.html)fore, we need a clean screenshot showing SuperOffice CRM in full view, for example:

![image](https://user-images.githubusercontent.com/22498774/208680601-d9fe7bee-a4c2-4a50-8c4e-3d4d7acfd073.png)

This is an example of how not to create a screenshot. 
![image](https://user-images.githubusercontent.com/22498774/208680654-fe023abc-dd58-435c-9101-bdb56ac6cbc9.png)

If you would like to know more about how to create the best screenshot, then click [here](https://mailto:tisha.bernadina@superoffice.com/).
If you need help creating the screenshots, click here to contact your friendly App Store team."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [dp-app-images-and-videos](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/developer-portal/app-store/images-and-videos.md/#L1)

**Comment by digitaldiina** [comment]
Resolved by PR https://github.com/SuperOfficeDocs/superoffice-docs/pull/569
